/// Date dimension, 2024-2026, generated in M. The model date table. Relates to every daily fact, and to the weekly email fact via week_start.
table DimDate
	lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d
	dataCategory: Time

	/// Date, at day grain. The key of the model's date table.
	column Date
		dataType: dateTime
		isKey
		formatString: dd/MM/yyyy
		lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Year, 4-digit.
	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	/// Quarter within the year: Q1-Q4. Not unique across years - use YearQuarter on an axis.
	column Quarter
		dataType: string
		lineageTag: 0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f50
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	/// Month as a number, 1-12. Sort column for MonthName.
	column Month
		dataType: int64
		formatString: 0
		lineageTag: 1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5061
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	/// Month name, en-GB (January to December) - set by Date.MonthName(..., "en-GB") in the
	/// partition M, so it does not follow the viewer's locale. Sorted by Month, not alphabetically.
	column MonthName
		dataType: string
		lineageTag: 2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f506172
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	/// Year-month as YYYY-MM (e.g. 2025-06). Sorted by YearMonthNr. The default month axis.
	column YearMonth
		dataType: string
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617283
		summarizeBy: none
		sourceColumn: YearMonth
		sortByColumn: YearMonthNr

		annotation SummarizationSetBy = Automatic

	/// Year-quarter as YYYY-Qn (e.g. 2025-Q2). Sorted by YearQuarterNr.
	column YearQuarter
		dataType: string
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617284
		summarizeBy: none
		sourceColumn: YearQuarter
		sortByColumn: YearQuarterNr

	/// Sort key for YearQuarter (Year*10 + quarter).
	column YearQuarterNr
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617285
		summarizeBy: none
		sourceColumn: YearQuarterNr

		annotation SummarizationSetBy = Automatic

	/// Sort key for YearMonth (Year*100 + month). Must have the same cardinality as YearMonth
	/// (one value per month) or Power BI sub-groups the axis by Date underneath.
	column YearMonthNr
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617286
		summarizeBy: none
		sourceColumn: YearMonthNr

		annotation SummarizationSetBy = Automatic

	/// Week of year, Monday-start. Range 1-53.
	column Week
		dataType: int64
		formatString: 0
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617287
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	/// Week label, "W01" to "W53", for weekly trend axes. Sorted by YearWeekNr.
	column YearWeek
		dataType: string
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617288
		summarizeBy: none
		sourceColumn: YearWeek
		sortByColumn: YearWeekNr

	/// Sort key for YearWeek (Year*100 + week).
	column YearWeekNr
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f50617289
		summarizeBy: none
		sourceColumn: YearWeekNr

		annotation SummarizationSetBy = Automatic

	/// Month offset relative to TODAY(): 0 = current month, -1 = last month, +1 = next month.
	/// For rolling windows (last 12 months = -11..0). Recomputed on every refresh - note this makes
	/// it move over time, so it is unsuitable for the fixed 2024-07..2025-06 analysis period.
	column 'Month Offset' = ( YEAR ( DimDate[Date] ) - YEAR ( TODAY () ) ) * 12 + ( MONTH ( DimDate[Date] ) - MONTH ( TODAY () ) )
		dataType: int64
		formatString: 0
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f5061728a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Drill-down hierarchy for charts: Year -> Quarter -> Month. Uses the UNIQUE columns
	/// (YearQuarter "2025-Q2", YearMonth "2025-06") rather than Quarter/MonthName, so that
	/// "go to next level" works - otherwise Power BI aggregates every year together.
	/// Month-start of each date. Bridge column so cohort_month (a month-grain key on
	/// CohortLTV / CohortRetention) can be TREATAS-mapped onto the daily calendar.
	/// Hidden - not for direct use.
	column MonthStart = DATE ( YEAR ( DimDate[Date] ), MONTH ( DimDate[Date] ), 1 )
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 4145863f-c6d9-4786-abc6-6699cf4aa375
		summarizeBy: none

	hierarchy 'Date Hierarchy'
		lineageTag: 4b5c6d7e-8f9a-4b5c-6d7e-8f9a0b1c2d3e

		level Year
			lineageTag: 5c6d7e8f-9a0b-4c5d-7e8f-9a0b1c2d3e4f
			column: Year

		level Quarter
			lineageTag: 6d7e8f9a-0b1c-4d6e-8f9a-0b1c2d3e4f50
			column: YearQuarter

		level Month
			lineageTag: 7e8f9a0b-1c2d-4e7f-9a0b-1c2d3e4f5061
			column: YearMonth

	/// Date dimension built in M from List.Dates over an explicit 2024-2026 window. Covers the 2024-07-01 to 2025-06-30 data period with headroom. Adjust the bounds in the partition source if the window needs to grow. No DAX calculated columns: every output column comes from Table.AddColumn in M.
	partition DimDate = m
		mode: import
		source =
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2026, 12, 31),
				    Days = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, Days, #duration(1, 0, 0, 0)),
				    Source = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    TypedDate = Table.TransformColumnTypes(Source, {{"Date", type date}}),
				    AddYear = Table.AddColumn(TypedDate, "Year", each Date.Year([Date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    AddMonth = Table.AddColumn(AddQuarter, "Month", each Date.Month([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date], "en-GB"), type text),
				    AddYearMonth = Table.AddColumn(AddMonthName, "YearMonth", each Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"), type text),
				    AddYearQuarter = Table.AddColumn(AddYearMonth, "YearQuarter", each Text.From(Date.Year([Date])) & "-Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    AddYearQuarterNr = Table.AddColumn(AddYearQuarter, "YearQuarterNr", each Date.Year([Date]) * 10 + Date.QuarterOfYear([Date]), Int64.Type),
				    AddYearMonthNr = Table.AddColumn(AddYearQuarterNr, "YearMonthNr", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    AddWeek = Table.AddColumn(AddYearMonthNr, "Week", each Date.WeekOfYear([Date], Day.Monday), Int64.Type),
				    AddYearWeek = Table.AddColumn(AddWeek, "YearWeek", each "W" & Text.PadStart(Text.From(Date.WeekOfYear([Date], Day.Monday)), 2, "0"), type text),
				    AddYearWeekNr = Table.AddColumn(AddYearWeek, "YearWeekNr", each Date.Year([Date]) * 100 + Date.WeekOfYear([Date], Day.Monday), Int64.Type)
				in
				    AddYearWeekNr

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

